[mongodb]
uri = "mongodb+srv://aliyashal309_db_user:ux2jWX2jhaVPEZT7@taskflocluster.vk3jqiu.mongodb.net/?retryWrites=true&w=majority&appName=taskFloCluster"

[smtp]
SMTP_SERVER="smtp.gmail.com"
SMTP_PORT=587
SENDER_EMAIL="yashalalifarooqui30@gmail.com"
SENDER_PASSWORD="reehyysqqgbgujyy"
